language: php
php:
  - '7.0'
  - '7.1'

script:
   - composer install
   - vendor/bin/phpunit

env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"

notifications:
    slack: epsi-ic:Q5TUTkIv6U8rufTM3TFZk80J